mkdir pkg &&
mkdir pacman-repo &&
cd pacman-repo &&
mkdir repo &&
cd .. &&
cd pkg &&
git clone https://aur.archlinux.org/brave-nightly-bin.git
git clone https://aur.archlinux.org/brave-bin.git
git clone https://aur.archlinux.org/brave-beta-bin.git
git clone https://aur.archlinux.org/yay-bin.git
git clone https://aur.archlinux.org/ventoy-bin.git
git clone https://aur.archlinux.org/waterfox-g-bin.git
git clone https://aur.archlinux.org/waterfox-g4-bin.git
git clone https://aur.archlinux.org/pycharm-community-jre.git
git clone https://aur.archlinux.org/slack-desktop.git
git clone https://aur.archlinux.org/heroic-games-launcher-bin.git
git clone https://aur.archlinux.org/jetbrains-fleet.git
git clone https://aur.archlinux.org/android-studio.git
git clone https://aur.archlinux.org/anydesk-bin.git
git clone https://aur.archlinux.org/inxi.git 
git clone https://aur.archlinux.org/armcord-bin.git 

