name: Autobuild Packages

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  buildpkg:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - run: pacman -Sy wget git sudo fakeroot --noconfirm
      - run: sh git_clone.sh
      - uses: pacman-repo-builder/action@<TAG>
        with:
          command: git clone https://github.com/phantomic12/openssl-1-files.git && cd openssl-1-files && mv libcrypto.so.1.1 libssl.so.1.1 /usr/lib && cd .. && rm -rf openssl-1-files build-pacman-repo build && sh genconf.sh
      - run: chmod +x /usr/local/bin/build-pacman-repo
      - run: tar --create -v pee.tar *.zst
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: pee.tar
          path: pee.tar
  upload-to-sourceforge:
    if: ${{ always() }}
    needs: [buildpkg]
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: fastai/workflows/ssh@master
      with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa
    - uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v3.0.0
    - name: Prepare for Upload
      run: |
        tar -xvf pee.tar
        rm pee.tar
        ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
        sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh *.zst "prtnic0924@frs.sourceforge.net:/home/pfs/project/phn-repo/1/x86_64/"
