name: Try building pacman on Ubuntu

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  buildpkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sh build-pac.sh