name: Try building pacman on Ubuntu

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  buildpkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install gdisk zip systemd-container bmap-tools asciidoc libarchive-tools git build-essential cmake libarchive-dev pkg-config libcurl4-openssl-dev libgpgme-dev libssl-dev fakeroot dh-autoreconf haveged os-prober kwalify dosfstools libisoburn1 zstd 
    - run: sudo python3 -m pip install meson
    - run: sudo python3 -m pip install ninja
    - run: sudo wget https://sources.archlinux.org/other/pacman/pacman-6.0.2.tar.xz
    - run: sudo tar -xvf pacman-6.0.2.tar.xz
    - run: pushd pacman-6.0.2
    - run: sudo meson --prefix=/usr \
                      --buildtype=plain \
                      -Ddoc=disabled \
                      -Ddoxygen=enabled \
                      -Dscriptlet-shell=/usr/bin/bash \
                      -Dldconfig=/usr/bin/ldconfig \
                      build
    - run: sudo meson compile -C build
    - run: sudo meson install -C build
    - run: popd
    - run: sudo install -m644 pacman.conf /etc/pacman.conf
    - run: sudo install -m644 makepkg.conf /etc/
    - run: sudo mkdir -p /etc/pacman.d
    - run: sudo touch /etc/pacman.d/mirrorlist
    - run: popd
    - run: mkdir -p archlinux-keyring
    - run: pushd archlinux-keyring
    - run: wget https://archlinux.org/packages/core/any/archlinux-keyring/download -O /tmp/archlinux-keyring.tar.zst
    - run: tar --use-compress-program=unzstd --strip-components=4 --wildcards -xvf /tmp/archlinux-keyring.tar.zst usr/share/pacman/keyrings/*
    - run: sudo install -m0644 archlinux.gpg /usr/share/pacman/keyrings/
    - run: sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
    - run: sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
    - run: popd  
    - run: sudo pacman-key --init
    - run: sudo pacman-key --populate archlinux

    - run: try and build binary to see what happens
    - run: git clone https://github.com/phantomic12/pacman-repo-builder &&
    - run: sudo apt-get -y install cargo &&
    - run: cd pacman-repo-builder &&
    - run: cargo build
