name: SF and OSDN upload test

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
# osdn key is also sourceforge key
jobs:
  buildpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh temp.sh
      - name: Setup SSH
        uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY_OSDN }}
          key_file: id_rsa
      - uses: pacman-repo-builder/action@0.0.0-rc.63
        with:
          command: cd 1 && build-pacman-repo init-aur-builder && cat build-pacman-repo.yaml && build-pacman-repo build
      - run: cd 1 && cd pacman-repo && ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts && sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh --inplace repo prtnic0924@frs.sourceforge.net:/home/pfs/project/phn-repo/1/
      - run: rsync -ar repo phantomic12@storage.osdn.net:/storage/groups/p/pf/phantomic12/phn-repo/test