name: osdn

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  buildpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh temp.sh
      - run: |
          echo "## ssh setup"
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          
      - uses: pacman-repo-builder/action@0.0.0-rc.63
        with:
          command: cd 10 && build-pacman-repo init-aur-builder && cat build-pacman-repo.yaml && build-pacman-repo build
      - run: |          
          ssh-keyscan -t rsa storage.osdn.net >> /home/runner/.ssh/known_hosts
          echo "iPq047cYUbQfAh5EBPSwbTg5+YjjugA6iOS8NGI8Hvw" >> /home/runner/.ssh/github_actions
          ssh-add /home/runner/.ssh/github_actions
      
      - run: cd 10 && cd pacman-repo && rsync -ar -e  repo phantomic12@fstorage.osdn.net:/storage/groups/p/pf/phantomic12/phn-repo/10/