name: Autobuild 10th set of packages

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  buildpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh temp.sh
      - run: |
        ssh-keyscan -t ed25519 frs.sourceforge.net >> /home/runner/.ssh/known_hosts
        echo "AAAAC3NzaC1lZDI1NTE5AAAAIMV6fPpi2WMr+wnH4ANBa0QNROgNG813DyAI8nxxp2gT" >> /home/runner/.ssh/github_actions
        ssh-add /home/runner/.ssh/github_actions

        ssh-keyscan -t rsa storage.osdn.net >> /home/runner/.ssh/known_hosts
        echo "iPq047cYUbQfAh5EBPSwbTg5+YjjugA6iOS8NGI8Hvw" >> /home/runner/.ssh/github_actions
        ssh-add /home/runner/.ssh/github_actions

        
      - uses: pacman-repo-builder/action@0.0.0-rc.63
        with:
          command: cd 10 && build-pacman-repo init-aur-builder && cat build-pacman-repo.yaml && build-pacman-repo build
      - run: cd 10 && cd pacman-repo && sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh repo prtnic0924@frs.sourceforge.net:/home/pfs/project/phn-repo/10/
      - run: rsync -ar -e  repo phantomic12@fstorage.osdn.net:/storage/groups/p/pf/phantomic12/phn-repo/10/