name: Test Packages

# add o once complete

n:
  push:
    branches: [redo]

jobs:
  buildpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa
      - uses: pacman-repo-builder/action@0.0.0-rc.63
        with:
          command: cd test && build-pacman-repo init-aur-builder && cat build-pacman-repo.yaml && build-pacman-repo build
      - run: cd test && cd pacman-repo && ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts && sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh --inplace repo prtnic0924@frs.sourceforge.net:/home/pfs/project/phn-repo/1/